language: go

go:
  - 1.8
  - tip

install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --exclude="rice-box.go" --tests ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)