baseurl = "https://hacdias.github.io/aprenda-a-programar/"
disqusShortname = "aprendaaprogramar"
languageCode = "pt_PT"
pluralizelisttitles = false
removePathAccents = true
title = "Aprenda a Programar"
image = "metterqqrcoisa"

[author]
  Email = "hacdias@gmail.com"
  Name = "Henrique Dias"
  Facebook = "hacdias"
  Twitter = "hacdias"
  GitHub = "hacdias"
  GooglePlus = "HenriqueDias"
  Instagram = "hacdias"
  LinkedIn = "hacdias"
  YouTube = "UCEJe-YgDEvr351w1oNjzolw"

[params]
  Description = "Aprenda a Programar é um extenso tutorial que tem como objetivo ensinar o leitor a programar. Não uma linguagem, mas a programar!"
