baseurl = "https://hacdias.github.io/aprenda-a-programar/"
disqusShortname = "hacdias"
languageCode = "pt_PT"
paginate = "18"
paginatePath = "page"
pluralizelisttitles = false
removePathAccents = true
title = "Aprenda a Programar"

[author]
  Email = "hacdias@gmail.com"
  Image = "henrique.png"
  JobTitle = "Author"
  Name = "Henrique Dias"
  Telephone = "351 965 856 140"

[params]
  Analytics = "59697241-1"
  Description = "Henrique Dias is a portuguese young student who loves to code and wants to help the humankind. Author at Pplware. Loves music too."
  Image = "home"
  [params.Webmaster]
    Bing = "B471CBBC9EF6900039C6BBF251EF277C"
    Google = "nVQ4_x6m6ZTRAzclMPNxpB0iMgK-xoIj_d-l85u32nY"

[social]
  Facebook = "hacdias"
  GitHub = "hacdias"
  GooglePlus = "HenriqueDias"
  Instagram = "hacdias"
  LinkedIn = "hacdias"
  Twitter = "hacdias"
  YouTube = "UCEJe-YgDEvr351w1oNjzolw"
