baseurl: 'https://notes.hacdias.com/'
languageCode: en
paginate: 10
rssLimit: 20
pluralizelisttitles: false
removePathAccents: true
title: "@hacdias' garden"
summarylength: 30
relativeURLs: true
enableRobotsTXT: true
summaryLength: 150

social:
  twitter: hacdias

params:
  emoji: ðŸ§™â€â™‚ï¸
  Description: >-
    This is Henrique Dias' digital garden with nodes made by him for him. He likes
    to share his thoughts and notes with others and this is the way he found to do so.

disableKinds:
  - taxonomy
  - term

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
    
outputs:
  home:
    - html
  section:
    - html
  page:
    - html
